config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :polls do
    resources :results
    resources :poll_answers do
      resources :votes
    end
  end

  root "polls#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/poll.rb
class Poll < ApplicationRecord
  has_many :poll_answers
  has_many :votes
end

app/models/poll_answer.rb
class PollAnswer < ApplicationRecord
  belongs_to :poll
  has_many :votes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  has_many :polls
  has_many :votes
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :poll_answer
  belongs_to :poll
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/poll_answers_controller.rb
class PollAnswersController < ApplicationController
  def new
    @poll = Poll.find(params[:poll_id])
    @answer = @poll.poll_answers.build
  end

  def create
    @poll = Poll.find(params[:poll_id])

    @answer = @poll.poll_answers.build(answer_params)

    if @answer.save
      redirect_to @poll, notice: "Answer was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def answer_params
    params.require(:poll_answer).permit(:answer)
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: [:show]

  # GET /polls
  def index
    @polls = Poll.includes(:votes).where(user_id: current_user.id).or(Poll.includes(:votes).where(votes: {user_id: current_user.id}))
  end

  # GET /polls/1
  def show
  end

  # GET /polls/new
  def new
    @poll = Poll.new
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  def create
    @poll = Poll.new(poll_params.merge(user_id: current_user.id))

    if @poll.save
      redirect_to @poll, notice: "Poll was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /polls/1
  def update
    if @poll.update(poll_params)
      redirect_to @poll, notice: "Poll was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /polls/1
  def destroy
    @poll.destroy
    redirect_to polls_url, notice: "Poll was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_poll
    @poll = Poll.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def poll_params
    params.require(:poll).permit(:question)
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    @poll = Poll.find(params[:poll_id])
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @vote = Vote.new(poll_id: params[:poll_id], poll_answer_id: params[:poll_answer_id], user_id: current_user.id)

    respond_to do |format|
      if current_user.votes.where(poll_id: params[:poll_id]).any?
        format.html { redirect_to poll_results_url(@vote.poll), notice: "You already voted" }
      elsif @vote.save
        format.html { redirect_to poll_results_url(@vote.poll), notice: "Vote was successfully created." }
      else
        format.html { redirect_to poll_url(@vote.poll), notice: "Something went wrong" }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimplePoll</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <% if user_signed_in? %>
      <div class="menu">
        <ul>
          <li><%= link_to "All polls", polls_path %>        </li>
          <li><%= link_to "New poll", new_poll_path %>        </li>
          <li><%= link_to "Logout", destroy_user_session_path %>        </li>
        </ul>
        </div>
        <% end %>
    <%= yield %>
  </body>
</html>

app/views/poll_answers/new.html.erb
<h1>New answer for poll</h1>

<%= form_with(model: [@poll, @answer]) do |form| %>
    <% if @answer.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this poll from being saved:</h2>

        <ul>
          <% @answer.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :answer, style: "display: block" %>
      <%= form.text_field :answer %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>


<br>

<div>
  <%= link_to "Back to poll", poll_path(@poll) %>
</div>

app/views/polls/_form.html.erb
<%= form_with(model: poll) do |form| %>
  <% if poll.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
        <% poll.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :question, style: "display: block" %>
    <%= form.text_field :question %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/polls/_poll.html.erb
<div id="<%= dom_id poll %>">
  <p>
    <strong>Question:</strong>
    <%= poll.question %>
  </p>
  <% poll.poll_answers.each do |pa| %>
    <%= button_to pa.answer, poll_poll_answer_votes_path(poll_id: poll.id, poll_answer_id: pa.id), method: :post %>
  <%end %>

</div>

app/views/polls/edit.html.erb
<h1>Editing poll</h1>

<%= render "form", poll: @poll %>

<br>

<div>
  <%= link_to "Show this poll", @poll %> |
  <%= link_to "Back to polls", polls_path %>
</div>

app/views/polls/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Polls</h1>

<div id="polls">
  <% @polls.each do |poll| %>
    <%= render poll %>
    <p>
      <%= link_to "Show this poll", poll %>
    </p>
    <p>
      <%= link_to "Show results", poll_results_url(poll) %>
    </p>
    <hr>
  <% end %>
</div>

<%= link_to "New poll", new_poll_path %>

app/views/polls/new.html.erb
<h1>New poll</h1>

<%= render "form", poll: @poll %>

<br>

<div>
  <%= link_to "Back to polls", polls_path %>
</div>

app/views/polls/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @poll %>

<div>
  <% if @poll.user_id == current_user&.id %>
    <%= link_to "Add answer to this pool", new_poll_poll_answer_path(@poll) %> |
    <%= link_to "Edit this poll", edit_poll_path(@poll) %> |
  <% end %>
  <%= link_to "Back to polls", polls_path %>

  <% if @poll.user_id == current_user&.id %>
    <%= button_to "Destroy this poll", @poll, method: :delete %>
  <% end %>
</div>

app/views/results/index.html.erb
<p style="color: green"><%= notice %></p>
<div id="<%= dom_id @poll %>">
  <p>
    <strong>Question:</strong>
    <%= @poll.question %>
  </p>
  <p> All votes: <%= @poll.votes.count %> </p>
  <% @poll.poll_answers.each do |pa| %>
    <% if pa.votes.any? %>
      <p> <%= pa.answer %> <%= (pa.votes.count.to_f/@poll.votes.count.to_f*100).to_i %>% (<%= pa.votes.count %>)</p>
    <% else %>
    <p> <%= pa.answer %> (<%= pa.votes.count %>)</p>

    <% end %>

  <%end %>

</div>
<%= link_to "New poll", new_poll_path %>
<%= link_to "Back to polls", polls_path %>